export const TEXTS = [
  "leatherback turtle",
  "winter jacket in the underground",
  "patterns on public transport seats",
  "paving stones in the park",
  "mud in spring",
  "bare trees",
  "patches on asphalt",
  "full painting teacher",
  "colourful mould on trunks",
  "stone in the field",
  "a shovel in a puddle",
  "a plank on the parquet",
  "shadow",
  "blue suit and long arms",
  "tucked-in trousers",
  "metal bucket",
  "green clock",
  "soviet concrete block",
  "horse and apple",
  "chair and kettle",
  "parquet and dust",
  "boxing bag",
  "target in the yard",
  "thin bushes",
  "sink, toothpick, cockroach",
  "trainers",
  "green dog",
  "blue whiskers of a hound",
  "coloured shadows",
  "velvet tracksuit with eagle",
  "blue plastic table",
  "grey down jacket and jeans",
  "snowfall in the yard, dog on a leash",
  "rock shadow",
  "spaceship",
  "cool boots",
  "cage",
  "purple urn",
  "ice and earth",
  "metal railing",
  "brickwork and growth suit",
  "mushroom",
  "car and panel",
  "wooden folding chair",
  "lemon on a plate",
  "tree and blue pipe",
  "imperial urn",
  "banana on a bench",
  "bird dog on four legs",
  "helmet with horns",
  "fluted metal shells",
  "bird standing on a car",
  "ladybird and dog nose",
  "branch-turn",
  "stupa",
  "hat with feather",
  "man with a cloud",
  "two tall men on the Clear Ponds",
  "a fox and a poplar",
  "green chair and avant-garde lamp",
  "a bird and a palm tree",
  "green cowboy and wasteland",
  "bicycle and driftwood",
  "platypus and red hand",
  "bicycle and purple roofs",
  "jin by the roadside",
  "kung fu against the table",
  "reese and headdress",
  "mermaid and umbrella",
  "dog with shadow",
  "superman on a bicycle",
  "white castle",
  "lobster and carnation",
  "brown suit",
  "puddle",
  "asphalt",
  "mobile phone",
  "sport suit",
  "magic nose",
  "underground plafond",
  "a stump and a fool",
  "washing agents",
  "barefoot and a brick",
  "blue cupboard",
  "blue branches",
  "olive under the lamp",
  "palm tree in the living room",
  "heels and laces",
  "pink car",
  "industrial area and tree",
  "finger and olive",
  "adverts on the fence",
  "tea on a stump",
  "may day",
  "baobab and zippo",
  "fridge in the garden",
  "dog begging",
  "multi-storeys and supermarket",
  "racing car",
  "pipe stove",
  "laptop and paws",
  "election and snowdrift",
  "noses in the air",
  "yoga mat",
  "apple tree",
  "khrushchevka and mountains",
  "a dog and a pill",
  "a gulch and a fool",
  "beard",
  "green suit",
  "tangerine with a sticker",
  "shaggy",
  "green nose",
  "divots on the parquet",
  "grand piano",
  "kettle on legs",
  "heart",
  "knight vs. monster",
  "runner",
  "thoughtful",
  "green man",
  "dog in thought",
  "dragon dog",
  "manticore",
  "tired horse",
  "cucumber and long face",
  "driftwood",
  "bad weather",
  "storm",
  "stars and puddles",
  "mud and frost",
  "whistling",
  "woollen ears",
  "sitting on the floor",
  "dangling my feet",
  "tempest",
];
